### ISSUE TITLE
Laravel Vapor failing to load assets with separate-vendor

### ISSUE THREAD

**Issue by ellisio** [DarkaOnLine/L5-Swagger#277]
- L5-Swagger Version: 7.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4.2
- OS: AWS Lambda

### Description:

When using `separate-vendor: true` and deploying with Laravel Vapor, assets will not load. Attempting to load the CSS results in the following exception:

```
ErrorException: file_get_contents(): Filename cannot be empty
#46 /tmp/vendor/darkaonline/l5-swagger/src/Http/Controllers/SwaggerAssetController.php(17): Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
#45 [internal](0): file_get_contents
#44 /tmp/vendor/darkaonline/l5-swagger/src/Http/Controllers/SwaggerAssetController.php(17): L5Swagger\Http\Controllers\SwaggerAssetController::index
#43 [internal](0): call_user_func_array
#42 /tmp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Illuminate\Routing\Controller::callAction
#41 /tmp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\ControllerDispatcher::dispatch
#40 /tmp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\Route::runController
#39 /tmp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route::run
#38 /tmp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Router::Illuminate\Routing\{closure}
#37 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#36 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#35 /tmp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Routing\Router::runRouteWithinStack
#34 /tmp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router::runRoute
#33 /tmp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router::dispatchToRoute
#32 /tmp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router::dispatch
#31 /tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
#30 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#29 /app/Http/Middleware/SentryContext.php(28): App\Http\Middleware\SentryContext::handle
#28 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#27 /app/Http/Middleware/DetectLocale.php(31): App\Http\Middleware\DetectLocale::handle
#26 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#25 /tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#24 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#23 /tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#22 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#21 /tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Foundation\Http\Middleware\ValidatePostSize::handle
#20 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#19 /tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
#18 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#17 /tmp/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Fruitcake\Cors\HandleCors::handle
#16 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#15 /tmp/vendor/fideloper/proxy/src/TrustProxies.php(57): Fideloper\Proxy\TrustProxies::handle
#14 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#13 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#12 /tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
#11 /tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel::handle
#10 /tmp/vendor/laravel/vapor-core/src/Runtime/HttpKernel.php(60): Laravel\Vapor\Runtime\HttpKernel::Laravel\Vapor\Runtime\{closure}
#9 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#8 /tmp/vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureVanityUrlIsNotIndexed.php(16): Laravel\Vapor\Runtime\Http\Middleware\EnsureVanityUrlIsNotIndexed::handle
#7 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#6 /tmp/vendor/laravel/vapor-core/src/Runtime/Http/Middleware/RedirectStaticAssets.php(30): Laravel\Vapor\Runtime\Http\Middleware\RedirectStaticAssets::handle
#5 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#4 /tmp/vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureOnNakedDomain.php(39): Laravel\Vapor\Runtime\Http\Middleware\EnsureOnNakedDomain::handle
#3 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#2 /tmp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#1 /tmp/vendor/laravel/vapor-core/src/Runtime/HttpKernel.php(61): Laravel\Vapor\Runtime\HttpKernel::handle
#0 /httpHandler.php(58): null
```

### Steps To Reproduce:

1. Add `separate-vendor: true` to your `vapor.yaml`.
2. Run `vapor deploy`
3. Attempt to load `https://<your-domain>/docs/asset/swagger-ui.css`.

**Comment by ellisio** [comment]
This flag exports `vendor` and mounts the directory at run time. I don't understand how this could make a difference. Perhaps it is a symlink issue? I think the vendor directory gets mounted to `/tmp/vendor` and then symlinked into the Lambda function.

**Comment by DarkaOnLine** [comment]
You should be able to change the assets path in the config: https://github.com/DarkaOnLine/L5-Swagger/blob/7.x/config/l5-swagger.php#L109

**Comment by ellisio** [comment]
@DarkaOnLine That did the trick! For those who stumble upon this issue when using `separate-vendor: true` you will want to add the following to your `.env.{env}` files for Vapor:

```
L5_SWAGGER_UI_ASSETS_PATH=../../tmp/vendor/swagger-api/swagger-ui/dist/
```

🤘

**Comment by Gustaf-Hard** [comment]
This worked perfectly for me also. 
But I also had to set an env variable `L5_SWAGGER_USE_ABSOLUTE_PATH=false`
