### ISSUE TITLE
Class resource does not exist

### ISSUE THREAD

**Issue by frijj2k** [DarkaOnLine/L5-Swagger#58]
Hi,

I have installed as per the documentation with example annotations and it appears to work OK.

However, if I manually call:  **php artisan l5-swagger:generate**

I get:

```
[ErrorException]               
Class resource does not exist  

```

Apart from this error, the documentation seems to get generated and works OK but I am unsure what is causing and if it will cause problems down the line.

I'm running Laravel 5.2.45 and installed package "darkaonline/l5-swagger": "~3.0"

Any ideas?

Thanks!

**Comment by tajulasri** [comment]
im also having the same problem.Do you found the any solution ?

**Comment by DarkaOnLine** [comment]
Could you please provide `laravel.log` file ?

- Empty the file `echo "" > storage/logs/laravel.log` (or simple open and delete content)
- Run `php artisan l5-swagger:generate `
- Copy/Paste the content of laravel.log for me, please.

**Comment by tajulasri** [comment]
@DarkaOnLine this is exception trace on verbose mode same as inside log.

```
Exception trace:
 () at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\zircote\swagger-php\src\Logger.php:38
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
 trigger_error() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\zircote\swagger-php\src\Logger.php:38
 Swagger\Logger->Swagger\{closure}() at n/a:n/a
 call_user_func() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\zircote\swagger-php\src\Logger.php:59
 Swagger\Logger::warning() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\zircote\swagger-php\src\Analyser.php:110
 Swagger\Analyser->fromComment() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\zircote\swagger-php\src\StaticAnalyser.php:254
 Swagger\StaticAnalyser->analyseComment() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\zircote\swagger-php\src\StaticAnalyser.php:118
 Swagger\StaticAnalyser->fromTokens() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\zircote\swagger-php\src\StaticAnalyser.php:33
 Swagger\StaticAnalyser->fromFile() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\zircote\swagger-php\src\functions.php:41
 Swagger\scan() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\darkaonline\l5-swagger\src\Generator.php:24
 L5Swagger\Generator::generateDocs() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\darkaonline\l5-swagger\src\Console\GenerateDocsCommand.php:32
 L5Swagger\Console\GenerateDocsCommand->fire() at n/a:n/a
 call_user_func_array() at E:\Codes\nazrol-tech\msc-evaluation-api\bootstrap\cache\compiled.php:1257
 Illuminate\Container\Container->call() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\laravel\framework\src\Illuminate\Console\Command.php:169
 Illuminate\Console\Command->execute() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\symfony\console\Command\Command.php:256
 Symfony\Component\Console\Command\Command->run() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\laravel\framework\src\Illuminate\Console\Command.php:155
 Illuminate\Console\Command->run() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\symfony\console\Application.php:794
 Symfony\Component\Console\Application->doRunCommand() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\symfony\console\Application.php:186
 Symfony\Component\Console\Application->doRun() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\symfony\console\Application.php:117
 Symfony\Component\Console\Application->run() at E:\Codes\nazrol-tech\msc-evaluation-api\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:107
 Illuminate\Foundation\Console\Kernel->handle() at E:\Codes\nazrol-tech\msc-evaluation-api\artisan:35
```

**Comment by DarkaOnLine** [comment]
Like you see this exception is due to the Swagger-php. So I think you have a mistake in your annotations.

**Comment by tajulasri** [comment]
btw if im using direct command line its working as well and im not writing any further annotation except for info() only so far. Does php docs annotation cause conflict during generation?

**Comment by salamza** [comment]
I happen to have the same error and I can't even generate the json file. 
I am pretty sure there's no mistakes in the annotations, since executing ` vendor/bin/swagger  app -o public/swagger.json` generates the json file successfully.

I am using Laravel 5.4.25 and l5-swagger 5.0.2

**Comment by DarkaOnLine** [comment]
@salamza can you show your exception trace?

Maybe try `php artisan optimize` command? I am trying to help blindly here :)

**Comment by salamza** [comment]
Of course, appreciate it :). 
```
ErrorException: Class resource does not exist 
in /home/vagrant/app/vendor/zircote/swagger-php/src/Logger.php:38
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(512, 'Class resource ...', '/home/vagrant/i...', 38, Array)
#1 /home/vagrant/app/vendor/zircote/swagger-php/src/Logger.php(38): trigger_error('Class resource ...', 512)
#2 [internal function]: Swagger\Logger->Swagger\{closure}('Class resource ...', 512)
#3 /home/vagrant/app/vendor/zircote/swagger-php/src/Logger.php(59): call_user_func(Object(Closure), Object(ReflectionException), 512)
#4 /home/vagrant/app/vendor/zircote/swagger-php/src/Analyser.php(110): Swagger\Logger::warning(Object(ReflectionException))
#5 /home/vagrant/app/vendor/zircote/swagger-php/src/StaticAnalyser.php(254): Swagger\Analyser->fromComment('/**\n * Class Fo...', Object(Swagger\Context))
#6 /home/vagrant/app/vendor/zircote/swagger-php/src/StaticAnalyser.php(118): Swagger\StaticAnalyser->analyseComment(Object(Swagger\Analysis), Object(Swagger\Analyser), '/**\n * Class Fo...', Object(Swagger\Context))
#7 /home/vagrant/app/vendor/zircote/swagger-php/src/StaticAnalyser.php(33): Swagger\StaticAnalyser->fromTokens(Array, Object(Swagger\Context))
#8 /home/vagrant/app/vendor/zircote/swagger-php/src/functions.php(41): Swagger\StaticAnalyser->fromFile('/home/vagrant/i...')
#9 /home/vagrant/app/vendor/darkaonline/l5-swagger/src/Generator.php(24): Swagger\scan('/home/vagrant/i...', Array)
#10 /home/vagrant/app/vendor/darkaonline/l5-swagger/src/Console/GenerateDocsCommand.php(32): L5Swagger\Generator::generateDocs()
#11 [internal function]: L5Swagger\Console\GenerateDocsCommand->fire()
#12 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#17 /home/vagrant/app/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /home/vagrant/app/vendor/symfony/console/Application.php(869): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/app/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(L5Swagger\Console\GenerateDocsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/app/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/app/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
```

**Comment by DarkaOnLine** [comment]
@salamza maby you are still using `@SWG\Resource` annotation? [It is deprecated](https://github.com/zircote/swagger-php/blob/master/docs/Migrating-to-v2.md)

**Comment by salamza** [comment]
@DarkaOnLine Nop, I double checked. Also, bear in mind that the swagger command generate the json file  with no complaints at all. 

On another note, I was able to generate the json file normally using `l5-swagger:generate` on my other Linux/laradock environment but it throws an error on my Windows/Homestead environment, despite it being the same code base from the same repo.

**Comment by jvihrial** [comment]
I would like to comment here (running Laravel 5.4 with the latest l5-swagger). The Resource annotation causes the that dialog for sure. BUT: it does not have to be @SWG\Resource, normal @Resource is enough to trigger this.

**Comment by gquende** [comment]
same error here
![image](https://github.com/DarkaOnLine/L5-Swagger/assets/43283373/e1418aeb-14d8-4da2-a92a-bbccf61cbc3d)
